language: ruby
rvm:
- 2.2.3
before_install: gem install bundler -v 1.11.2

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: jsonapi_errorable
  on:
    tags: true
    repo: jsonapi-suite/jsonapi_errorable
